language: python
python:
  - "3.5"
install:
  - pipenv install
script: 
  - nosetests --with-coverage --cover-package=app
  - coveralls
branches:
  except:
  - master
  only:
  - challenge2
after_success:
 - coveralls
notifications:
  email: false