language: python
python:
  - "3.5"
install:
  - pipenv install
script: 
  - nosetests --with-coverage --cover-package=app tests/
  - coveralls
branches:
  except:
  - master
  only:
  - develop
after_success:
 - coveralls
notifications:
  email: false
