language: python
python:
  - "3.5"
install:
  - pipenv install
  - pipenv install coveralls
script: 
  - nosetests --with-coverage --cover-package=app
  - coveralls
branches:
  only:
  - challenge2
after_success:
 - coveralls
notifications:
  email: false